server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: dev

logging:
  level:
    spring.security: DEBUG #로깅 레벨 설정

springdoc:
  packages-to-scan : spring.security
  swagger-ui :
    path :  ${SPRINGDOC_SWAGGER_PATH} # html 문서 접속 경로
    tags-sorter : alpha # 태그 정렬 기준
    operations-sorter : alpha # alpha (알파벳 오름차순), method (HTTP 메소드 순)
    doc-expansion: none # tag, operation 펼치는 방식
  api-docs :
    path : ${SPRINGDOC_API_PATH}
    groups :
      enabled : true
  cache :
    disabled : true
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8